---
language: python
dist: bionic
python:
  - "2.7"
  - "3.6"
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
