---
- name: Installing package
  package:
    name: sudo
    state: present

- name: Get sudo version
  shell: set -o pipefail && sudo -V 2>&1 | egrep '^Sudo ' | sed -r 's/.* ([0-9]*\.[0-9]*\.[0-9]*).*/\1/g'
  args:
    executable: /bin/bash
  changed_when: false
  register: sudo_version
  check_mode: no

- name: Create sudoers.d directory
  file:
    path: "/etc/sudoers.d"
    owner: "root"
    group: "root"
    mode: "0750"
    state: directory

- name: Install main config
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    owner: "root"
    group: "root"
    mode: "0440"
    validate: 'visudo -cf %s'

- name: List files in /etc/sudoers.d
  find:
    paths: "/etc/sudoers.d"
    patterns: "*"
  register: sudoers_contents
  changed_when: false

- name: Remove unmanaged /etc/sudoers.d/ files
  file:
    path: "/etc/sudoers.d/{{ item.path|basename }}"
    state: absent
  loop: "{{ sudoers_contents.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - (item.path|basename) not in roles
...
